### ISSUE TITLE
png2jpg 报错

### ISSUE THREAD

**Issue by sheepzh** [Algebra-FUN/WeReadScan#15]
如果章节篇幅过长，该方法会报错

```
Maximum supported image dimension is 65500 pixels
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    weread.scan2pdf('https://weread.qq.com/web/reader/d2332cf05b3a64d2302db21')
  File "/home/zhy/.local/lib/python3.6/site-packages/WeReadScan/WeRead.py", line 219, in scan2pdf
    jpg_name = png2jpg(png_name, binary_threshold, quality)
  File "/home/zhy/.local/lib/python3.6/site-packages/WeReadScan/script/png2pdf.py", line 20, in png2jpg
    # 这里
    Image.fromarray(dst).save(f'{file_name}.jpg', quality=quality)
  File "/home/zhy/.local/lib/python3.6/site-packages/PIL/Image.py", line 2164, in save
    save_handler(self, fp, filename)
  File "/home/zhy/.local/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 761, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/home/zhy/.local/lib/python3.6/site-packages/PIL/ImageFile.py", line 544, in _save
    raise OSError(f"encoder error {s} when writing image file")
OSError: encoder error -2 when writing image file
```

jpeg 规范只用了 4 字节存储像素大小，所以文件太大不行的，可以考虑直接用 png 转pdf ？

**Comment by sheepzh** [comment]
或者可以新增一个参数，不用生成 pdf，因为对我来说 png 已经够用了（为了导入 OCR 识别里面的内容 ）

**Comment by Algebra-FUN** [comment]
你可修改一下源代码
WeRead.py, 函数scan2pdf，250-252行
```python
        # convert to pdf and save offline
        img2pdf(f'{save_at}/{book_name}', png_name_list)
        print('scanning finished.')
```
这里是调用输出pdf的代码部分，删掉即可，或者你自己加一个disable参数也行
还有就是方法执行完会清楚临时文件，可以设置`debug=True`，来保留临时文件
也欢迎你可以把OCR的功能整合进去，共同打造一个更好的项目
（我本来也是打算做OCR，这个项目最早是疫情期间为了解决找书难的问题而开发的；奈何现在回到学校，就可以去图书馆借书，个人的需求没了……）

**Comment by sheepzh** [comment]
好的，我抽空把选择输出方式的 feature 加上吧，到时候 PR 过来

**Comment by sheepzh** [comment]
另外，我 OCR 一般调云服务。
