### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by arctic-han** [Algebra-FUN/WeReadScan#2]
driver: WebDriver = Chrome(chrome_options=chrome_options)

改成：driver: WebDriver = Chrome(options=chrome_options)
可正常运行

启动 Webdriver 时 ：

C:\Users\Arcti\AppData\Local\Programs\Python\Python38\python.exe C:/Users/Arcti/Desktop/WeReadScan/example/demo.py
C:/Users/Arcti/Desktop/WeReadScan/example/demo.py:23: DeprecationWarning: use options instead of chrome_options
  driver: WebDriver = Chrome(chrome_options=chrome_options)
Webdriver launching...
Traceback (most recent call last):
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\request.py", line 79, in request
    return self.request_encode_body(
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 51, in create_connection
    host, port = "address"
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Arcti/Desktop/WeReadScan/example/demo.py", line 23, in <module>
    driver: WebDriver = Chrome(chrome_options=chrome_options)
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 83, in __init__
    self.quit()
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 158, in quit
    self.service.stop()
  File "C:\Users\Arcti\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 147, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

Process finished with exit code 1

如何去设置修改这些文件？ 
才疏学浅，可否把文件打包成exe文件方便学习。

**Comment by Algebra-FUN** [comment]
1. 这个可能与Chrome和ChromeDriver的版本有关，请问你的Chrome和ChromeDriver的版本是什么？
2. 我不明白“打包成exe文件”如何方便学习，python程序打包后运行效率没有提升，相反程序还会比较大（相比于脚本）

**Comment by arctic-han** [comment]
> 1. 这个可能与Chrome和ChromeDriver的版本有关，请问你的Chrome和ChromeDriver的版本是什么？
> 2. 我不明白“打包成exe文件”如何方便学习，python程序打包后运行效率没有提高，相反程序将会比较大（引用于脚本）

![image](https://user-images.githubusercontent.com/63783466/99968285-ed72b880-2dd3-11eb-8c1f-693eca196c2e.png)
一直说模块引用出了问题但是所有的模块都有，语法也对。不知道那里的问题

**Comment by arctic-han** [comment]
> 1. 这个可能与Chrome和ChromeDriver的版本有关，请问你的Chrome和ChromeDriver的版本是什么？
> 2. 我不明白“打包成exe文件”如何方便学习，python程序打包后运行效率没有提升，相反程序还会比较大（相比于脚本）


------------------------------------------------
不像是驱动的问题，驱动可以打开浏览器。chrome是版本87.0.4280.66，驱动是，87.0.4280.20
![image](https://user-images.githubusercontent.com/63783466/99974609-26169000-2ddc-11eb-90d0-4b7a4aec3922.png)

**Comment by arctic-han** [comment]
> 1. 这个可能与Chrome和ChromeDriver的版本有关，请问你的Chrome和ChromeDriver的版本是什么？
> 2. 我不明白“打包成exe文件”如何方便学习，python程序打包后运行效率没有提升，相反程序还会比较大（相比于脚本）


第一台电脑驱动打不开浏览器，换了台电脑，驱动可以打开浏览器。图片均来自第二台电脑。

**Comment by arctic-han** [comment]
> > 1. 这个可能与Chrome和ChromeDriver的版本有关，请问你的Chrome和ChromeDriver的版本是什么？
> > 2. 我不明白“打包成exe文件”如何方便学习，python程序打包后运行效率没有提升，相反程序还会比较大（相比于脚本）
> 
> 第一台电脑驱动打不开浏览器，换了台电脑，驱动可以打开浏览器。图片均来自第二台电脑。

**Comment by Algebra-FUN** [comment]
关于options的问题：
你是对的，经过查阅相关资料，发现_"chrome_options is deprecated now and you have to use options instead as well as pass the absolute path of the ChromeDriver along with the extension."_chrome_options已经被弃用
所以我已经把代码中的chrome_options替换为options，感谢你的issue
顺便一提，chrome_options在我的设备上运行并没有warning
关于这个DeprecationWarning，可以参考StackOverflow上的解答：https://stackoverflow.com/questions/63310119/deprecationwarning-use-options-instead-of-chrome-options-error-using-chromedriv

**Comment by arctic-han** [comment]
> 关于options的问题：
> 你是对的，经过查阅相关资料，发现_"chrome_options is deprecated now and you have to use options instead as well as pass the absolute path of the ChromeDriver along with the extension."_chrome_options已经被弃用
> 所以我已经把代码中的chrome_options替换为options，感谢你的issue
> 顺便一提，chrome_options在我的设备上运行并没有warning
> 关于这个DeprecationWarning，可以参考StackOverflow上的解答：https://stackoverflow.com/questions/63310119/deprecationwarning-use-options-instead-of-chrome-options-error-using-chromedriv

好的，谢谢您的回复。非常感谢您！

**Comment by Algebra-FUN** [comment]
关于“TypeError:'model' object is not callable”这个Error:
是由于“from WeReadScan import WeRead”这行代码引起的
你应该是下载了repo之后运行的代码，这就会出现路径问题，推荐使用pip install WeReadScan进行依赖安装，这样导入的时候就是绝对导入而不是相对导入，就不会有路径问题

**Comment by arctic-han** [comment]
> 关于“TypeError:'model' object is not callable”这个Error:
> 是由于“from WeReadScan import WeRead”这行代码引起的
> 你应该是下载了repo之后运行的代码，这就会出现路径问题，推荐使用pip install WeReadScan进行依赖安装，这样导入的时候就是绝对导入而不是相对导入，就不会有路径问题

嗯嗯，由于python自动更新到3.9  导致无法很好的使用pip，总会报错，所以下载了repo之后运行的

**Comment by arctic-han** [comment]
换到vscode上面可以正常运行没有更改的代码。

**Comment by Algebra-FUN** [comment]
> 换到vscode上面可以正常运行没有更改的代码。

巧了，我常用的就是vscode😀

**Comment by arctic-han** [comment]
> > 换到vscode上面可以正常运行没有更改的代码。
> 
> 巧了，我常用的就是vscode😀

建议把README添加上用vscode，pycharm对旧语法不支持了。对了，能否用邮件联系我一下（arctic_han@outlook.com），留个联系方式
