### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by duwenba** [Algebra-FUN/WeReadScan#39]
## 扫码后显示需要双重验证,需要在网页端输入验证码
![Snipaste_2023-07-28_11-13-54](https://github.com/Algebra-FUN/WeReadScan/assets/87513903/9e83758c-b251-48f8-b64b-ccb92da17a7e)
![2a0bd89439022e3807dde30c68a663f](https://github.com/Algebra-FUN/WeReadScan/assets/87513903/bbfb8b31-46f9-4eea-84c9-1c1699db5e96)

**Comment by duwenba** [comment]
## 手动验证后无法运行,输出信息如下:
```shell
$ python test.py
Webdriver launching...

DevTools listening on ws://127.0.0.1:1685/devtools/browser/60cf866d-3017-4119-ae2b-e1222c63d227
Webdriver launched.
Waiting for QRCode Scan...0/15turns
Waiting for QRCode Scan...1/15turns
Waiting for QRCode Scan...2/15turns
Login Succeed.
Traceback (most recent call last):
  File "d:\22753\duwenba\py\weread-scan\test.py", line 24, in <module>
    weread.scan2html('https://weread.qq.com/web/reader/452325f071ffa331452f4a8kc81322c012c81e728d9d180')
  File "D:\python3_10\lib\site-packages\WeReadScan\WeRead.py", line 189, in scan2html
    html = self.get_html(book_url)
  File "D:\python3_10\lib\site-packages\WeReadScan\WeRead.py", line 141, in get_html
    'Page.addScriptToEvaluateOnNewDocument', {'source': self.load_js('construct_root_and_observer')})
  File "D:\python3_10\lib\site-packages\WeReadScan\WeRead.py", line 60, in load_js
    with open(f'{self.path}\\js\\{name}.js','r',encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python3_10\\Lib\\site-packages\\WeReadScan\\js\\construct_root_and_observer.js'
```

**Comment by Algebra-FUN** [comment]
> ## 扫码后显示需要双重验证,需要在网页端输入验证码
> ![Snipaste_2023-07-28_11-13-54](https://user-images.githubusercontent.com/87513903/256713533-9e83758c-b251-48f8-b64b-ccb92da17a7e.png) ![2a0bd89439022e3807dde30c68a663f](https://user-images.githubusercontent.com/87513903/256713616-bbfb8b31-46f9-4eea-84c9-1c1699db5e96.jpg)

我自己真的没有遇到过需要双重验证的时候😅
