### ISSUE TITLE
大家现在还能爬出东西吗？

### ISSUE THREAD

**Issue by VSpade7** [Algebra-FUN/WeReadScan#42]
![image](https://github.com/Algebra-FUN/WeReadScan/assets/46594083/59ccd0c8-6635-47d3-afe3-e0bf14c8baf4)
不知道是不是被反爬了，如图，我现在已经爬不出主要内容了

**Comment by HiruTonbi** [comment]
近日微信读书爬虫都失效了。可以试试作者之前的网页截图png合成pdf的版本，在gitee上可以找得到，但效果肯定没有html版本好……

**Comment by icedme666** [comment]
可以，要改下库，因为前端改了原来的元素定位不好使了

**Comment by KangShanR** [comment]
Webdriver launching...
Webdriver launched.
Traceback (most recent call last):
  File "/home/k/Documents/codes/openai/python/weread_demo.py", line 20, in <module>
    weread.login() #? login for grab the whole book
  File "/home/k/.local/lib/python3.10/site-packages/WeReadScan/WeRead.py", line 103, in login
    self.S('button.navBar_link_Login').click()
  File "/home/k/.local/lib/python3.10/site-packages/WeReadScan/WeRead.py", line 70, in S
    return WebDriverWait(self.driver, self.patience).until(lambda driver: driver.find_element(By.CSS_SELECTOR, selector))
  File "/home/k/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x64c8f805e62e <unknown>
#1 0x64c8f7ac0226 <unknown>
#2 0x64c8f7b10627 <unknown>
#3 0x64c8f7b10991 <unknown>
#4 0x64c8f7b593a4 <unknown>
#5 0x64c8f7b362cd <unknown>
#6 0x64c8f7b5713f <unknown>
#7 0x64c8f7b36073 <unknown>
#8 0x64c8f7b039ef <unknown>
#9 0x64c8f7b046b1 <unknown>
#10 0x64c8f802e7f1 <unknown>
#11 0x64c8f80319f6 <unknown>
#12 0x64c8f803146b <unknown>
#13 0x64c8f8031ec5 <unknown>
#14 0x64c8f801bc7b <unknown>
#15 0x64c8f803228c <unknown>
#16 0x64c8f8005305 <unknown>
#17 0x64c8f804e2c8 <unknown>
#18 0x64c8f804e4ec <unknown>
#19 0x64c8f805da3c <unknown>
#20 0x6ffc45a94ac3 <unknown>
